engineer-man/piston

- readme.md
so at the top of the read me it says 
> that originates **from from** EMKC 
I changed it to say
> that originates **from** EMKC
> fixed this really annoying thing on the readme where you say from twice

- lxc/execute
- lxc/executors/emacs
- tests/test.el
Hi EM,
I tried to add support for executing elisp scripts through `emacs`.
This code is untested and it was written by studying what was already there.
Your server will need `emacs` installed in order for it to work.
Let me know if I did anything wrong!
> add support for elisp scripts

- api/main.go
- lxc/execute
- lxc/executors/nasm
- lxc/test_all_lxc
There is currently no way to distinguish between running 32-bit and 64-bit code in the assembly module so I decided to do something about it. 
I defaulted nasm/asm to 32-bit assembly as that is the more common form of assembly most people will be familiar with. I then
added the 64 bit assembly under the names nasm64 and asm64. 
The test file for nasm was already written in 32 bit assembly and would always fail since nasm was set to compile in 64 bit mode. I kept this same file and wrote a new test for 64 bit assembly.
As for the main.go file, "go format" was automatically run leading to the indentation being corrected to the go standards. I did not realize it until I pushed my commit, but I can undo that if you would like. Changes at line 81 and 155.
The "executing version" of the …
> Change ASM module to default to 32 bit and add 64 bit executor

- shared/execute.js
Stop appending to output if it already reached/is over the limit. The issue is that the program could run out of memory when commands with huge outputs like `yes` are executed. This commit should fix #52
> Stop appending to output if longer than limit

- lxc/execute
Preventing the user from spying on each other currently running code by chmoding and chowning runner folder so only the current runner can read from it.
Should not anyhow effect piston functionality.
> Prevent users from spying on each other

- lxc/executors/java
It should work better than grep. Works on interfaces and such. My only concern is the timeout, since compilation and execution are combined.
> Run Java directly to avoid grep

- lxc/executors/scala
Scala has colored compiler errors on by default which can't be rendered in places like the piston bot and causes compiler errors to become a big mess and makes it difficult to figure out what actually happened.
> Disable color output for scala

- lxc/executors/prolog
This PR gives command line arguments access to prolog programs via the main/1 predicate which accepts one list argument.
This predicate should be defined whenever arguments are given.
> call main\1 predicate with arguments list if any

- lxc/executors/deno
By default Deno has color output, we don't need this - and it also makes challenges on emkc.org not give the correct results.
> Disable color output for deno

- container/install_script.sh
- lxc/util/versions
Right now the scala version script invokes `scala` which starts the repl when it should actually ask `scalac` for the version.
> Fix scala version

- packages/init
Fix the v3 package init script to insert "$@" in run file.
> Fix package init script to use "$@" in run file instead of "$*"

- api/Dockerfile
Adds build-essential V3 API  container. Rust executor needs `cc` and libgcc_s in order to compile binaries.
> Add build-essential V3 API container 

- api/Dockerfile
- packages/rust/1.50.0/build.sh
- packages/rust/1.50.0/compile
- packages/rust/1.50.0/environment
- packages/rust/1.50.0/metadata.json
- packages/rust/1.50.0/run
- packages/rust/1.50.0/test.rs
Adds rust to v3. Needs build-essential in API container because `rustc` uses `cc` for linking. You can specify ld (pass `-C linker=ld` to rustc) to link, but linking still fails since ld can't find `gcc_s`.
> pkg(rust-1.50.0): Add rust 1.50.0

- packages/rust/1.50.0/run
pkg(rust-1.50.0): Fix run file to remove filename from being passed to binary
Needed to `shift` before running binary.
> pkg(rust-1.50.0): Fix run file to remove filename from being passed to binary

- api/src/nosocket/nosocket.c
Adds 32 bit arch to the seccomp filter - allowing them to run.
Fixes: 32 bit nasm code.
> Fixes nasm32 - adds 32bit arch to seccomp filter

- api/src/api/v2.js
- api/src/config.js
- api/src/job.js
- readme.md
Added an optional `max_memory_usage` parameter to limit the amount of memory a job is allowed to use. The default value and upper limit can be configured in `config.yaml`.
> Added max_memory_usage parameter

- api/Dockerfile
- repo/Dockerfile
deps for octave. FYI, this will nearly double the size of the api container. these are all heavy math libs that octave references to do cool math things.
and fortran is needed for building the source only
> pkg(octave-6.2.0): add deps for octave

- packages/zig/0.7.1/compile
such as the code below which should crash
```zig
var a: u8 = 255;
var b: u8 = 1;
var c: u8 = a + b;
```
> zig/0.7.1: set release most to safe so executers can still observe runtime checks

- api/src/api/v2.js
- api/src/config.js
- api/src/job.js
- readme.md
Added two independent optional parameters to limit the amount of memory the compile stage and the run stage of a job are allowed to use. The default values and upper limits can be configured in `config.yaml` and default to `-1` (no limit) to avoid any problems when using the default configuration.
> Improved memory limits

- readme.md
I created a [Node.js client wrapper](https://github.com/dthree/node-piston) to access the Piston API easily from Node. This makes it very easy to access the public Piston API or any private API from Node, hope you like it!
@realtux I don't mind moving this into the engineer-man account if you'd prefer that.
> Proposal: Add Piston Node.js Client as an Official Extension

- readme.md
I made a [Java wrapper](https://github.com/the-codeboy/Piston4J) to access the Piston API and when I saw [this](https://github.com/engineer-man/piston/pull/287) pullrequest I thought I might also try adding it as an official exstension
> Add Piston4J as an Official Extension

- packages/go/1.16.2/run
When you run a Go project ```go run $1.go``` only compiles and runs $1.go. To compile and run all files in the project we must do ```go run *.go```
> Fixed Go multiple file problem

- readme.md
I made an asynchronous API wrapper for Piston in Python and looking at the other 2 pull requests , I thought I might try as well to add it as an official extension . Hope you like it ! [Pyston repo](https://github.com/ffaanngg/pyston) and [documentation](https://ffaanngg.github.io/pyston/)
> Add Pyston as an official extension

- api/src/api/v2.js
I noticed that stdin wasn't working after rebuilding the latest changes locally. This should fix that.
I didn't test the new socket impl tho, since I wasn't able to connect to it on my local instance. @HexF , will this affect your latest web socket additions?
> fix stdin for normal execute

- packages/freebasic/1.8.0/build.sh
- packages/freebasic/1.8.0/compile
- packages/freebasic/1.8.0/environment
- packages/freebasic/1.8.0/metadata.json
- packages/freebasic/1.8.0/run
- packages/freebasic/1.8.0/test.bas
- readme.md
This was sitting in another branch too.. just needed to update readme and fix the version.
QBasic is DOS only. FreeBASIC is its successor and works on linux. I've set the compiler flags to compile QBasic programs.
fixes #288
> pkg(freebasic-1.8.0): Add Freebasic

- .github/workflows/package-pr.yaml
I noticed the CI is attempting to build an empty package every time. This checks that both the package name and package version exist before attempting to build it.
**Context**: Hexf found some invalid make commands trying to run. [discord message](https://discord.com/channels/473161189120147456/483979558249562112/893267864923013140)
> prevent building empty package on pr

- readme.md
This pull request adds [`piston_rs`](https://github.com/Jonxslays/piston_rs), an async Rust wrapper around the Piston API, to the readme as an officially supported extension.
I used Piston in a few of my bots, and love it. I was perusing the readme and realized there was a new section regarding supported extensions. I also noticed that there was no extension in Rust yet, so I decided to make one. 
- [Crate](https://crates.io/crates/piston_rs)
- [Documentation](https://docs.rs/piston_rs/latest)
- [Repository](https://github.com/Jonxslays/piston_rs)
> Add piston_rs to readme

- builder/build.sh
When running this script I noticed that the script would only work if you were already in the builder directory. This PR addresses that.
> Make builder script run relative to directory it was called from

- api/src/api/v2.js
- api/src/api/v3.js
- api/src/bin/pistond.js
- api/src/bin/test.js
- api/src/runtime.js
In the previous implementation, we used NodeJS module caching to simulate a globally shared `runtimes` state. In this implementation, we get rid of the global state and only provide the runtimes in `app.locals`. I think it makes more sense this way, and it allowed for code reusability.
> Refactor runtimes

- cli/commands/execute.js
A more or less naive algorithm in the CLI to check if the file is binary. This should work if the file contains non-ascii characters as well. Inspired by: https://stackoverflow.com/a/49773659
> Include non-ascii in CLI binary checking

- api/src/api/v2.js
- api/src/api/v3.js
- api/src/job.js
I made this in Piston V3, but I don't think there is a need to add it in Nix Piston. It has a limited use case and it can be replicated on the client side if needed.
> Get rid of file language logic, remove unneeded requires

- api/src/api/v2.js
- api/src/job.js
This could be breaking for some applications like `piston-bot`
closes #456
> Piston-Nix: Don't start run stage if compile stage errored

- readme.md
- runtimes/default.nix
- runtimes/j.nix
ok i think chose the right branch this time
> j nix package

- readme.md
This pull request adds [`piston_rspy`](https://github.com/Jonxslays/piston_rspy), to the README. `piston_rspy` provides bindings for `piston_rs` to Python developers.
- [Package](https://pypi.org/project/piston-rspy/)
- [Documentation](https://jonxslays.github.io/piston_rspy/piston_rspy/)
- [Repository](https://github.com/Jonxslays/piston_rspy)
> Add piston_rspy to the readme

- packages/rust/1.62.0/build.sh
- packages/rust/1.62.0/compile
- packages/rust/1.62.0/environment
- packages/rust/1.62.0/metadata.json
- packages/rust/1.62.0/run
- packages/rust/1.62.0/test.rs
Following template from #393 to bump the rust toolchain to the latest
stable
> pkg(rust-1.62.0): Added rust 1.62.0

- packages/deno/1.16.2/run
- packages/deno/1.7.5/run
deno's output coloring can cause side effects when we expect plain text. disable coloring of both deno runtimes
> disable output coloring of deno

- piston
```
user@work ~> find packages -depth 2
find: paths must precede expression: `2'
```
> bin(piston): Fix ./piston list-pkgs

- api/src/index.js
- repo/Dockerfile
- repo/entrypoint.sh
- repo/serve.py
The PID 1 processes in `piston_api` and `piston_repo` containers did not use to handle the `SIGTERM` signal causing Docker to timeout (after about 10 seconds) on stopping the containers and to `SIGKILL` them.
After this change, the containers now stop after about 0.5 seconds on my machine.
> Improve containers stopping performance by handling SIGTERM (95% improvement)

- packages/python/3.11.0/build.sh
- packages/python/3.11.0/environment
- packages/python/3.11.0/metadata.json
- packages/python/3.11.0/run
- packages/python/3.11.0/test.py
pycrypto is now no longer maintained, so replaced with pycryptodome
> Added files for Python 3.11.0

- api/src/job.js
This PR improves handling process kills. 
- Bugfix: Fixed error in catch block: `e is not defined` (Commit: dc4bb29)
- Moved other process kills inside `try-catch` blocks to handle `SIGKILL` for processes that are already dead. (Commit: d8af1ee)
> Handle process kills gracefully

- api/src/job.js
- docker-compose.dev.yaml
the checking of the length of the stdout and stderr was checking on the stdout and stderr before the addition of the data characters so it passes any length of characters as long as passing the limit is in the same buffer.
basically 
```
{
"language": "python3",
"version": "*",
"files": [
{
"name": "test",
"content": "print('h'*5000)"
}
],
"stdin": "2"
}
```
this passes when it shouldn't
> handle stdout and stderr limits properly

- packages/dart/3.0.1/build.sh
- packages/dart/3.0.1/environment
- packages/dart/3.0.1/metadata.json
- packages/dart/3.0.1/run
- packages/dart/3.0.1/test.dart
Checklist:
-   [x] The package builds locally with `./piston build-pkg dart 3.0.1`
-   [x] The package installs with `./piston ppman install dart=3.0.1`
-   [x] The package runs the test code with `./piston run dart -l 3.0.1 packages/dart/3.0.1/test.*`
-   [x] Package files are placed in the correct directory
-   [x] No old package versions are removed
-   [x] All source files are deleted in the `build.sh` script
-   [x] `metadata.json`'s `language` and `version` fields match the directory path
-   [x] Any extensions the language may use are set as aliases
-   [x] Any alternative names the language is referred to are set as aliases.
> add Dart 3.0.1 package

- api/src/job.js
- api/src/runtime.js
setuid binaries tend to disable variables like `LD_LIBRARY_PATH` to prevent arbitrary code execution with elevated privileges. As a result, `isolate` disables such variables and they are not passed to the process. This leads to problems in runtimes that have such variables in their environment such as gcc.
> Explicitly provide env vars instead of inheriting them from parent
