api/main.go
lxc/execute
lxc/executors/julia
lxc/versions
readme.md
tests/test.jl
tests/test_all_lxc

I added the support for Julia. Everything should be there.

Julia support

---

api/main.go
lxc/execute
lxc/executors/elixir
lxc/versions
readme.md
tests/test.exs
tests/test_all_lxc

This PR adds elixir support for piston, as well as erlang/23 OTP.
Instructions to get piston running on arch as added in the README too.

Add elixir support for piston

---

lxc/execute
lxc/executors/deno
lxc/executors/haskell
lxc/test_all_lxc
lxc/tests/test.hs
lxc/tests/testdeno.js
lxc/tests/testdeno.ts
lxc/versions
readme.md

Let me know if there is anything I need to change.

Deno and Haskell support

---

readme.md

Tried to make the project README pretty and easier to navigate.

README rewrite

---

readme.md

Compiles, passes tests, installs correctly.

Update PHP to 8.0.0

---

lxc/execute
shared/execute.js

Fixes #57. I tested it on my machine and it seems to work. Please test it and tell me if you find a bug.

Fix stdin lines

---

lxc/tests/awk.awk

fix awk test

---

lxc/executors/zig

Don't attempt to run executable if compilation fails

---

lxc/executors/brainfuck

I added a compilation step to the brainfuck executor, it gets about 9 seconds to compile and 3 to execute.

Fixes the brainfuck executor

---

config/languages.json
container/install_script.sh
lxc/executors/lolcode
lxc/tests/lolcode.lol
readme.md

Adds lolcode, needs testing.
Closes #138

Add lolcode

---

packages/julia/1.5.4/build.sh
packages/julia/1.5.4/environment
packages/julia/1.5.4/metadata.json
packages/julia/1.5.4/run
packages/julia/1.5.4/test.jl

Closes https://github.com/engineer-man/piston/issues/112

pkg(julia-1.5.4): Added julia 1.5.4

---

repo/Dockerfile

dependencies from apt-get for erlang

pkg(erlang-23.0.0): Add curses deps before adding lang

---

api/Dockerfile
packages/elixir/1.11.3/environment
packages/osabie/1.0.1/environment

Fixes #149 
Requires a rebuild of the api container (no-cache)

pkg(osabie-1.0.1/elixir-1.11.3): Fix VM warnings for osabie and elixir

---

api/Dockerfile

Needed before adding crystal build steps
After merge and api container rebuild then I'll add the rest in

pkg(crystal-0.36.1): Add deps to api container

---

api/Dockerfile

Necessary dependencies for the api container in order to add Haskell build steps

pkg(haskell-9.0.1): Add deps to api container

---

packages/lisp/2.1.2/build.sh
packages/lisp/2.1.2/environment
packages/lisp/2.1.2/metadata.json
packages/lisp/2.1.2/run
packages/lisp/2.1.2/test.cl

pkg(lisp-2.1.2): Add lisp (SBCL) 2.1.2

---

packages/haskell/9.0.1/build.sh
packages/haskell/9.0.1/compile
packages/haskell/9.0.1/environment
packages/haskell/9.0.1/metadata.json
packages/haskell/9.0.1/run
packages/haskell/9.0.1/test.hs

Fixes #115 
took more than half an hr to build on my machine --- let's see how this goes..

pkg(haskell-9.0.1): Add haskell 9.0.1

---

packages/osabie/1.0.1/run

pkg(osabie-1.0.1): Fix osabie args

---

packages/scala/3.0.0/build.sh
packages/scala/3.0.0/environment
packages/scala/3.0.0/metadata.json
packages/scala/3.0.0/run
packages/scala/3.0.0/test.scala

run will compile and run using `scala` binary. so it could fail the tests if it goes beyond 3s. hope it works..

pkg(scala-3.0.0): Add scala 3.0.0

---

api/Dockerfile

pkg(prolog-8.2.4): Add deps for prolog

---

api/Dockerfile

pkg(swift-5.3.3): Add deps for swift

---

packages/zig/0.7.1/build.sh
packages/zig/0.7.1/compile
packages/zig/0.7.1/environment
packages/zig/0.7.1/metadata.json
packages/zig/0.7.1/run
packages/zig/0.7.1/test.zig

pkg(zig-0.7.1): Add zig 0.7.1

---

shell.nix

Cleans up the nix syntax a bit.

Fix syntax error in shell.nix

---

packages/clojure/1.10.3/build.sh
packages/clojure/1.10.3/environment
packages/clojure/1.10.3/metadata.json
packages/clojure/1.10.3/run
packages/clojure/1.10.3/test.clj

pkg(clojure-1.10.3): Add clojure 1.10.3

---

packages/vlang/0.1.13/build.sh
packages/vlang/0.1.13/environment
packages/vlang/0.1.13/metadata.json
packages/vlang/0.1.13/run
packages/vlang/0.1.13/test.v

pkg(vlang-0.1.13): Add vlang 0.1.13

---

packages/rockstar/1.0.0/build.sh
packages/rockstar/1.0.0/environment
packages/rockstar/1.0.0/metadata.json
packages/rockstar/1.0.0/run
packages/rockstar/1.0.0/test.rock

pkg(rockstar-1.0.0): Add rockstar 1.0.0

---

packages/cow/1.0.0/build.sh
packages/cow/1.0.0/environment
packages/cow/1.0.0/metadata.json
packages/cow/1.0.0/run
packages/cow/1.0.0/test.cow

MoO MoO MoO MoO MoO MoO MoO
MoO MOO moO MoO MoO MoO MoO
MoO MoO MoO MoO MoO mOo MOo
moo moO Moo MoO Moo

pkg(cow-1.0.0): Add cow 1.0.0

---

packages/pascal/3.2.0/build.sh
packages/pascal/3.2.0/compile
packages/pascal/3.2.0/environment
packages/pascal/3.2.0/metadata.json
packages/pascal/3.2.0/run
packages/pascal/3.2.0/test.pp

pkg(pascal-3.2.0): Add pascal (FreePascal) 3.2.0

---

packages/coffeescript/2.5.1/build.sh
packages/coffeescript/2.5.1/environment
packages/coffeescript/2.5.1/metadata.json
packages/coffeescript/2.5.1/run
packages/coffeescript/2.5.1/test.coffee

pkg(coffeescript-2.5.1): Add coffeescript 2.5.1

---

packages/ponylang/0.39.0/build.sh
packages/ponylang/0.39.0/compile
packages/ponylang/0.39.0/environment
packages/ponylang/0.39.0/metadata.json
packages/ponylang/0.39.0/run
packages/ponylang/0.39.0/test.pony

```pony
actor Main
new create(env: Env) =>
env.out.print("Adds 🦄 pony 🦄 lang 🦄!")
```

pkg(pony-0.39.0): Add pony-lang 0.39.0

---

api/src/ppman/package.js
api/src/ppman/routes.js
cli/commands/ppman_commands/uninstall.js

It didn't work at first. now it does. and fixed some typos.

Fix uninstall

---

packages/dragon/1.9.8/build.sh
packages/dragon/1.9.8/environment
packages/dragon/1.9.8/metadata.json
packages/dragon/1.9.8/run
packages/dragon/1.9.8/test.dragon

fixes #203 
had to remake their install script to install locally, so hoping it works

pkg(dragon-1.9.8): Add dragon 1.9.8

---

packages/mono/6.12.0/compile
packages/mono/6.12.0/environment
packages/mono/6.12.0/metadata.json
packages/mono/6.12.0/run

pkg(mono-6.12.0): filename fixes

---

packages/gcc/10.2.0/build.sh
packages/gcc/10.2.0/compile
packages/gcc/10.2.0/environment
packages/gcc/10.2.0/metadata.json
packages/gcc/10.2.0/test.f90

Builds GCC to provide support for Fortran.

pkg(gcc-10.2.0): Adds Fortran support for GCC

---

packages/cobol/3.1.2/build.sh
packages/cobol/3.1.2/compile
packages/cobol/3.1.2/environment
packages/cobol/3.1.2/metadata.json
packages/cobol/3.1.2/run
packages/cobol/3.1.2/test.cob

Adds Cobol 3.1.2. Uses the gnucobol compiler.

pkg(cobol-3.1.2): Adds cobol 3.1.2 (gnucobol)

---

repo/Dockerfile

just added `libreadline-dev` and separated the rest on multiple lines for readability
after this is merged, I'll pr the build fix for lolcode

pkg(lolcode-0.11.2): add dep for correct version

---

packages/lolcode/0.11.2/build.sh

pkg(lolcode-0.11.2): update build script to use correct lolcode version

---

readme.md

As of #239 yeethon is now supported too

fix: add yeethon to supported languages list

---

api/src/api/v2.js
api/src/config.js
api/src/job.js
readme.md

Reverts engineer-man/piston#238

Revert "Added max_memory_usage parameter"

---

packages/rockstar/1.0.0/build.sh
packages/rockstar/1.0.0/environment
packages/rockstar/1.0.0/metadata.json
packages/rockstar/1.0.0/run

switching to Rocky (java implementation) in order to use it with stdin properly.
Rocky is a 100% implementation of the original Rockstar spec.

pkg(rockstar-1.0.0): switch to rocky implementation

---

packages/octave/6.2.0/metadata.json

Octave aliases/file extensions compliant to https://octave.org/doc/v6.2.0/Introduction-to-Function-and-Script-Files.html

pkg(octave-6.2.0): add aliases/file extensions

---

packages/scala/3.0.0/build.sh
packages/scala/3.0.0/compile
packages/scala/3.0.0/environment
packages/scala/3.0.0/metadata.json
packages/scala/3.0.0/run

adds compile phase, which mostly works now.
main issue is getting the entry point class name, so if anyone knows a better way, feel free to update it.

pkg(scala-3.0.0): use compile

---

packages/python/3.9.4/build.sh

add sympy to python 3.9.4

---

packages/zig/0.8.0/build.sh
packages/zig/0.8.0/compile
packages/zig/0.8.0/environment
packages/zig/0.8.0/metadata.json
packages/zig/0.8.0/run
packages/zig/0.8.0/test.zig

zig 0.8.0 got released, so this pr updates it
Closes #277

update zig to 0.8.0

---

packages/cow/1.0.0/build.sh

forked the original repo by BigZaphod and fixed the slurping issue when reading stdin for the Moo and oom commands

fixed slurp for COW lang

---

packages/mono/6.12.0/compile

pkg(mono-6.12.0): redirect mono compile errors to stderr

---

packages/vlang/0.1.13/run

Fixed a bug where the rename command would be called on the command line arguments as well.

pkg(vlang-0.1.13): Fix command line arguments bug

---

api/src/job.js

Old process janitor required starting a `ps` process.
This was problematic, as `ps` requires another entry in the process table, which in some cases was impossible as it was exhausted.

rework process janitor

---

cli/package-lock.json
packages/sqlite3/3.36.0/build.sh
packages/sqlite3/3.36.0/environment
packages/sqlite3/3.36.0/metadata.json
packages/sqlite3/3.36.0/run
packages/sqlite3/3.36.0/test.sql
readme.md

Executes the first file provided as a script.

pkg(sqlite3-3.36.0): Added sqlite3 3.36.0

---

api/src/api/v2.js
cli/package-lock.json
packages/iverilog/11.0.0/build.sh
packages/iverilog/11.0.0/compile
packages/iverilog/11.0.0/environment
packages/iverilog/11.0.0/metadata.json
packages/iverilog/11.0.0/run
packages/iverilog/11.0.0/test.verilog
readme.md
repo/Dockerfile

pkg(iverilog-11.0.0): Added iverilog 11.0.0

---

packages/rust/1.56.1/build.sh
packages/rust/1.56.1/compile
packages/rust/1.56.1/environment
packages/rust/1.56.1/metadata.json
packages/rust/1.56.1/run
packages/rust/1.56.1/test.rs

Sadly, I couldn't get the checks running, so there's might be problem with that.
Resolves #392

pkg(rust-1.56.1): Added rust 1.56.1

---

api/src/job.js

addresses: https://github.com/engineer-man/emkc/issues/176

Piston Nix: Add trailing newline in stdin if it doesn't exist

---

api/package.json
api/yarn.lock

Building Piston was failing
https://github.blog/2021-09-01-improving-git-protocol-security-github/

Piston-nix - package.json: don't use out-of-support unencrypted git protocol

---

packages/sqlite3/3.36.0/run

currently can't solve any problems that involve argv on emkc so this should fix that

sqlite3 add argv compitibility

---

readme.md
runtimes/default.nix
runtimes/forth.nix

forth nix package

---

api/src/job.js

Clear hanging timeouts and parent processes writables

---

packages/smalltalk/3.2.3/run

it needs -a flag or it thinks it's reading from multiple files or something

smalltalk fix argv

---

api/src/api/v2.js
api/src/job.js

fixes #500 
https://nodejs.org/api/child_process.html#event-close
Also prevents triggering a job cleanup when the client closes a websocket connection.

Concurrent jobs and websockets improvements

---

packages/rust/1.65.0/build.sh
packages/rust/1.65.0/compile
packages/rust/1.65.0/environment
packages/rust/1.65.0/metadata.json
packages/rust/1.65.0/run
packages/rust/1.65.0/test.rs

Checklist:
-   [x] The package builds locally with `./piston build-pkg [package] [version]`
-   [x] The package installs with `./piston ppman install [package]=[version]`
-   [x] The package runs the test code with `./piston run [package] -l [version] packages/[package]/[version]/test.*`
-   [x] Package files are placed in the correct directory
-   [x] No old package versions are removed
-   [x] All source files are deleted in the `build.sh` script
-   [x] `metadata.json`'s `language` and `version` fields match the directory path
-   [x] Any extensions the language may use are set as aliases
-   [x] Any alternative names the language is referred to are set as aliases.

pkg(rust-1.65.0): Added Rust 1.65.0

---

.github/workflows/api-push.yaml
.github/workflows/package-pr.yaml
.github/workflows/package-push.yaml
.github/workflows/repo-push.yaml

Update the actions in the GitHub Actions workflows to their latest versions.

chore(actions): update GitHub workflow actions

---

packages/rust/1.68.2/build.sh
packages/rust/1.68.2/compile
packages/rust/1.68.2/environment
packages/rust/1.68.2/metadata.json
packages/rust/1.68.2/run
packages/rust/1.68.2/test.rs

It shouldn't be a breaking change (I hope) because I'm not able to test it, so be careful when merging also if it should work

Updated to `Rust 1.68.2`

---

packages/deno/1.32.3/build.sh
packages/deno/1.32.3/environment
packages/deno/1.32.3/metadata.json
packages/deno/1.32.3/run
packages/deno/1.32.3/test.deno.ts

It shouldn't be a breaking change (I hope) because I'm not able to test it, so be careful when merging also if it should work

Updated to `Deno 1.32.3`

---

packages/typescript/5.0.3/build.sh
packages/typescript/5.0.3/compile
packages/typescript/5.0.3/environment
packages/typescript/5.0.3/metadata.json
packages/typescript/5.0.3/run
packages/typescript/5.0.3/test.ts

It shouldn't be a breaking change (I hope) because I'm not able to test it, so be careful when merging also if it should work

Updated to `Typescript 5.0.3`

---

api/src/api/v2.js
api/src/job.js

Backported to master the fix made by @Brikaa for better handling of parallel requests

Backport engineer-man#519 parallel requests fix

---

packages/python/3.12.0/build.sh
packages/python/3.12.0/environment
packages/python/3.12.0/metadata.json
packages/python/3.12.0/run
packages/python/3.12.0/test.py

Nothing of note to add, deployed locally and all works on my end.

Python 3.12.0 support

---

api/src/job.js

Provide HOME in sandbox
